typography_spectrum: 0.9365100397262722
color:
  brandStrength: 0.40437185554765165
  lightness: 0.8307795475702733
  saturation: 0.8000547506380826
  rhythmicContrast: 0.10892659402452409
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.5885022007860243
author:
  name: Elena
name: Declutterella
title: Make room for the life you want
